version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: lemp-nginx
    restart: always
    ports:
      - 8080:80
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ~/Documents/intranet-kraken/www:/var/www/html/website

  php:
    build: ./docker/php/
    container_name: lemp-php
    restart: always
    ports:
      - 9000:9000
    environment:
      - TZ=Europe/Paris
    volumes:
      - ~/Documents/intranet-kraken/www:/var/www/html/website

  database:
    image: mariadb:latest
    container_name: lemp-database
    restart: always
    ports:
     - 3306:3306
    environment:
      - TZ=Europe/Paris
      - MYSQL_ROOT_PASSWORD=azerty123
